### ISSUE TITLE
Problem installing in Linux

### ISSUE THREAD

**Issue by dmarrazzo** [snoussi/qlb-loan-application-ui#1]
I installed npm:
 
    sudo dnf install npm

When I launch `npm start`, I get this message:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.11.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle PatternFlyDemo@1.0.0~prestart: PatternFlyDemo@1.0.0
6 info lifecycle PatternFlyDemo@1.0.0~start: PatternFlyDemo@1.0.0
7 verbose lifecycle PatternFlyDemo@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle PatternFlyDemo@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/node-gyp-bin:/home/donato/git/demo/qlb-loan-application-ui/node_modules/.bin:/usr/share/Modules/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/home/donato/.local/bin:/home/donato/bin
9 verbose lifecycle PatternFlyDemo@1.0.0~start: CWD: /home/donato/git/demo/qlb-loan-application-ui
10 silly lifecycle PatternFlyDemo@1.0.0~start: Args: [ '-c', 'gulp' ]
11 info lifecycle PatternFlyDemo@1.0.0~start: Failed to exec start script
12 verbose stack Error: PatternFlyDemo@1.0.0 start: `gulp`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules.bundled/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid PatternFlyDemo@1.0.0
14 verbose cwd /home/donato/git/demo/qlb-loan-application-ui
15 verbose Linux 4.16.11-300.fc28.x86_64
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v8.11.2
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error PatternFlyDemo@1.0.0 start: `gulp`
23 error spawn ENOENT
24 error Failed at the PatternFlyDemo@1.0.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]
```

**Comment by dmarrazzo** [comment]
Ok solved.

```
sudo npm install -g grunt-cli
# maybe the next is redundant
npm install patternfly --save 
npm install angular-patternfly --save
```
TODO: update the doc

Reference: https://www.npmjs.com/package/angular-patternfly

**Comment by snoussi** [comment]
Thank you @dmarrazzo ! 
I have updated the README.
